from __future__ import annotations

RENDER_W, RENDER_H = 240, 160
WINDOW_SCALE = 4
WIDTH, HEIGHT = RENDER_W * WINDOW_SCALE, RENDER_H * WINDOW_SCALE

# Horizontal field-of-view in degrees.
FOV = 75.0

# Packed local index: idx = lx | (lz << 4) | (ly << 8).
# With CHUNK_SIZE=16 and CHUNK_HEIGHT=16 this fits in uint16.
CHUNK_SIZE = 16
CHUNK_HEIGHT = 16
WATER_LEVEL = 4
NOISE_SCALE = 0.1
NOISE_OCTAVES = 4
NOISE_PERSISTENCE = 0.5
NOISE_LACUNARITY = 2.0
HEIGHT_BASE = 5
HEIGHT_AMP = 3

BLOCK_MAX_DIST = 16
BLOCK_LOD_ENABLE = True
BLOCK_LOD_NEAR_CHUNKS = 1.5
BLOCK_LOD_MID_CHUNKS = 2.5
BLOCK_LOD_FAR_CHUNKS = 3.5

BLOCK_AIR = 0
BLOCK_BEDROCK = 1
BLOCK_DIRT = 2
BLOCK_WATER = 3
BLOCK_TRUNK = 4
BLOCK_LEAVES = 5

ID_TO_COLOR = {
    BLOCK_BEDROCK: (80, 80, 80),
    BLOCK_DIRT: (120, 90, 60),
    BLOCK_WATER: (0, 0, 180),
    BLOCK_TRUNK: (80, 50, 40),
    BLOCK_LEAVES: (40, 80, 40),
}
COLOR_TO_ID = {v: k for k, v in ID_TO_COLOR.items()}

SKY_COLOR = (135, 206, 235)
GRASS_COLOR = (34, 139, 34)

MOUSE_SENSITIVITY = 0.003
PLAYER_HEIGHT = 2.0
PLAYER_HALF_WIDTH = 0.5
GRAVITY = -20.0
JUMP_IMPULSE = 7.0
SPEED = 16.0

VIEW_RADIUS = 1
VIEW_RADIUS_Y_UP = 1
VIEW_RADIUS_Y_DOWN = 3
FPS_LIMIT = 144

# Demo tuning for billboard entities.
BUNNY_MOVEMENT_ENABLED = False
BUNNY_SPAWN_CHANCE = 0.2
FLOWER_PATCH_CHANCE = 0.01
FLOWER_PATCH_MIN = 4
FLOWER_PATCH_MAX = 8
FLOWER_PATCH_RADIUS_MIN = 1.0
FLOWER_PATCH_RADIUS_MAX = 2.4
